theme: jekyll-theme-architect
---
title: Avash Neupane
---
description: [I’m a Data Science Master’s student from University at Buffalo graduating in December 2022. I’m actively looking for full-time job opportunities.]
