theme: jekyll-theme-minimal
title: Avash Neupane
logo: /image_50404865.JPG
description: [# Skills
- **Programming Languages:** Python, R, SQL, MATLAB
- **Database, Analytics & Visualization:** MS SQL, MySQL, PostgreSQL, SQLite, Excel, Tableau
- **Data Science and Machine Learning:** Numpy, Pandas, Matplotlib, Seaborn, Pytorch, Scikit-Learn, TensorFlow, Keras, OpenCV, RDKit, RShiny Dashboard
- **Version Control:** Git]
