theme: jekyll-theme-minimal
title: Avash Neupane
logo: /pp.JPG
description: [ [Email Me]'avash.neupane01@gmail.com' | [LinkedIn: Lets Connect](https://www.linkedin.com/in/avash-neupane/) I’m a Data Science Master’s student from University at Buffalo graduating in December 2022. I’m actively looking for full-time job opportunities.]
